# Generated by Django 4.0.3 on 2022-04-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marque', models.CharField(max_length=100)),
                ('Modèle', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=4)),
                ('Capacité', models.CharField(max_length=20)),
            ],
        ),
    ]
