# Generated by Django 4.0.3 on 2022-04-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='SN',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
