# Generated by Django 4.0.3 on 2022-05-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_ram_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marque', models.CharField(max_length=100)),
                ('Modèle', models.CharField(max_length=100)),
                ('Fréquence', models.CharField(max_length=4)),
                ('SN', models.CharField(max_length=20)),
            ],
        ),
    ]
