# Generated by Django 4.0.3 on 2022-05-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_marque_type_alter_cpu_fréquence_alter_cpu_marque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marque',
            old_name='miaou',
            new_name='Marque',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='miaou',
            new_name='Type',
        ),
    ]
